X <- matrix(runif(10*20), nrow=10, ncol=20)
Y <- matrix(runif(10*15), nrow=10, ncol=15)

out1 <- PLSSVD(X, Y, k=2)
out2 <- PLSSVD(X, Y, deflation=TRUE, k=2)
out3 <- PLSSVD(X, Y, fullrank=TRUE, k=2)
out4 <- PLSSVD(X, Y, deflation=TRUE, fullrank=TRUE, k=2)
out5 <- PLSSVD(X, Y, k=2, cortest=TRUE)

expect_equal(dim(out1$scoreX), c(nrow(X), 2))
expect_equal(dim(out1$loadingX), c(ncol(X), 2))
expect_equal(length(out1$d), 2)
expect_equal(dim(out1$scoreY), c(nrow(Y), 2))
expect_equal(dim(out1$loadingY), c(ncol(Y), 2))

expect_equal(dim(out2$scoreX), c(nrow(X), 2))
expect_equal(dim(out2$loadingX), c(ncol(X), 2))
expect_equal(length(out2$d), 2)
expect_equal(dim(out2$scoreY), c(nrow(Y), 2))
expect_equal(dim(out2$loadingY), c(ncol(Y), 2))

expect_equal(dim(out3$scoreX), c(nrow(X), 2))
expect_equal(dim(out3$loadingX), c(ncol(X), 2))
expect_equal(length(out3$d), 2)
expect_equal(dim(out3$scoreY), c(nrow(Y), 2))
expect_equal(dim(out3$loadingY), c(ncol(Y), 2))

expect_equal(dim(out4$scoreX), c(nrow(X), 2))
expect_equal(dim(out4$loadingX), c(ncol(X), 2))
expect_equal(length(out4$d), 2)
expect_equal(dim(out4$scoreY), c(nrow(Y), 2))
expect_equal(dim(out4$loadingY), c(ncol(Y), 2))

expect_equal(dim(out5$scoreX), c(nrow(X), 2))
expect_equal(dim(out5$loadingX), c(ncol(X), 2))
expect_equal(length(out5$d), 2)
expect_equal(dim(out5$scoreY), c(nrow(Y), 2))
expect_equal(dim(out5$loadingY), c(ncol(Y), 2))
expect_equal(dim(out5$corX), c(ncol(X), 2))
expect_equal(dim(out5$corY), c(ncol(Y), 2))
expect_equal(dim(out5$pvalX), c(ncol(X), 2))
expect_equal(dim(out5$pvalY), c(ncol(Y), 2))
expect_equal(dim(out5$qvalX), c(ncol(X), 2))
expect_equal(dim(out5$qvalY), c(ncol(Y), 2))
